// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WS.MVC.Data.Context;

#nullable disable

namespace WS.MVC.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230810211005_migration-initial")]
    partial class migrationinitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WS.MVC.Models.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("WS.MVC.Models.ProductModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<sbyte>("IsProductActive")
                        .HasColumnType("TINYINT")
                        .IsFixedLength();

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("INT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("WS.MVC.Models.ProductModel", b =>
                {
                    b.HasOne("WS.MVC.Models.CategoryModel", "GetCategoryModel")
                        .WithMany("GetProductModels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetCategoryModel");
                });

            modelBuilder.Entity("WS.MVC.Models.CategoryModel", b =>
                {
                    b.Navigation("GetProductModels");
                });
#pragma warning restore 612, 618
        }
    }
}
